export const paintingData = [
  // Front Wall (0-4)
  {
    imgSrc: '/artworks/0.jpg',
    width: 5,
    height: 3,
    position: { x: -15, y: 2, z: -19.5 },
    rotationY: 0,
    info: {
      title: 'Good-bye My Loneliness',
      artist: '坂井泉水，栗林诚一郎',
      description: 'ZARD1991年出道之作,清澈嗓音与动人旋律交织,主打歌告别孤独,融合摇滚与J-Pop,销量超20万张,奠定乐坛经典地位。',
      year: '1991.02.10',
      link: 'https://github.com/fightagainstdev',
    },
  },
  {
    imgSrc: '/artworks/1.jpg',
    width: 5,
    height: 3,
    position: { x: -7.5, y: 2, z: -19.5 },
    rotationY: 0,
    info: {
      title: '不思議ね… ',
      artist: '坂井泉水',
      description: 'ZARD1991年第二张专辑，清亮嗓音搭配轻快旋律，融合流行与摇滚元素，展现青春活力与情感细腻，销量可观，巩固ZARD在日本乐坛的地位。',
      year: '1991-06-25',
      link: 'https://github.com/fightagainstdev',
    },
  },
  {
    imgSrc: '/artworks/2.jpg',
    width: 5,
    height: 3,
    position: { x: 0, y: 2, z: -19.5 },
    rotationY: 0,
    info: {
      title: 'もう探さない ',
      artist: 'zard',
      description: 'ZARD1991年第三张专辑，坂井泉水清澈嗓音诉说深情，融合J-Pop与摇滚，旋律动人，情感真挚，展现青春与梦想，销量不俗，进一步奠定ZARD乐坛地位。',
      year: '1991-12-25',
      link: 'https://github.com/fightagainstdev',
    },
  },
  {
    imgSrc: '/artworks/3.jpg',
    width: 5,
    height: 3,
    position: { x: 7.5, y: 2, z: -19.5 },
    rotationY: 0,
    info: {
      title: '眠れない夜を抱いて ',
      artist: 'zard',
      description: 'ZARD1992年第四张专辑，坂井泉水嗓音清亮动人，融合J-Pop与摇滚，旋律抒情温暖，诉说深夜思绪与情感，销量优异，确立ZARD在日本乐坛的稳固地位。',
      year: '1992-08-05',
      link: 'https://github.com/fightagainstdev',
    },
  },
  {
    imgSrc: '/artworks/4.jpg',
    width: 5,
    height: 3,
    position: { x: 15, y: 2, z: -19.5 },
    rotationY: 0,
    info: {
      title: 'In My Arms Tonight ',
      artist: 'zard',
      description: 'ZARD1993年单曲专辑，坂井泉水清澈嗓音传递深情，融合J-Pop与摇滚，旋律柔美动人，诉说爱与思念，深受乐迷喜爱，巩固ZARD在日本乐坛的影响力。',
      year: '1993-12-16',
      link: 'https://github.com/fightagainstdev',
    },
  },
  {
    imgSrc: '//artworks/5.jpg',
    width: 5,
    height: 3,
    position: { x: -15, y: 2, z: 19.5 },
    rotationY: Math.PI,
    info: {
      title: '負けないで',
      artist: 'zard',
      description: 'ZARD1993年单曲专辑，坂井泉水清亮嗓音激励人心，融合J-Pop与摇滚，旋律振奋，传递坚持与希望，深受乐迷喜爱，进一步巩固ZARD在日本乐坛的经典地位。',
      year: '1993-01-27',
      link: 'https://github.com/fightagainstdev',
    },
  },
  {
    imgSrc: '/artworks/6.jpg',
    width: 5,
    height: 3,
    position: { x: -7.5, y: 2, z: 19.5 },
    rotationY: Math.PI,
    info: {
      title: '君がいない',
      artist: 'zard',
      description: 'ZARD1993年单曲专辑，坂井泉水嗓音清澈动人，融合J-Pop与抒情摇滚，旋律温柔诉说思念与失落，情感真挚，广受好评，持续巩固ZARD在日本乐坛的影响力。',
      year: '1993-04-21',
      link: 'https://github.com/fightagainstdev',
    },
  },
  {
    imgSrc: '/artworks/7.jpg',
    width: 5,
    height: 3,
    position: { x: 0, y: 2, z: 19.5 },
    rotationY: Math.PI,
    info: {
      title: '揺れる想い',
      artist: 'zard',
      description: 'ZARD1993年第五张专辑，坂井泉水清澈嗓音诉说爱与感伤，融合J-Pop与摇滚，旋律动人，情感细腻，销量突破百万，确立ZARD在日本乐坛的顶尖地位。',
      year: '1993-07-10',
      link: 'https://github.com/fightagainstdev',
    },
  },
  // Back Wall (5-9)
  {
    imgSrc: '/artworks/8.jpg',
    width: 5,
    height: 3,
    position: { x: 7.5, y: 2, z: 19.5 },
    rotationY: Math.PI,
    info: {
      title: 'もう少し あと少し… ',
      artist: 'zard',
      description: 'ZARD1994年第六张专辑，坂井泉水嗓音清亮动人，融合J-Pop与摇滚，旋律温暖励志，诉说坚持与希望，销量优异，进一步巩固ZARD在日本乐坛的经典地位。',
      year: '1993-09-04',
      link: 'https://github.com/fightagainstdev',
    },
  },
  {
    imgSrc: '/artworks/9.jpg',
    width: 5,
    height: 3,
    position: { x: 15, y: 2, z: 19.5 },
    rotationY: Math.PI,
    info: {
      title: 'きっと忘れない ',
      artist: 'zard',
      description: 'ZARD1993年单曲专辑，坂井泉水清澈嗓音传递深情，融合J-Pop与抒情摇滚，旋律柔美动人，诉说难忘的思念与爱，广受乐迷喜爱，巩固ZARD在日本乐坛地位。',
      year: '1993-11-03',
      link: 'https://github.com/fightagainstdev',
    },
  },
  // Left Wall (10-14)
  {
    imgSrc: '/artworks/10.jpg',
    width: 5,
    height: 3,
    position: { x: -19.5, y: 2, z: -15 },
    rotationY: Math.PI / 2,
    info: {
      title: 'この愛に泳ぎ疲れても ',
      artist: 'zard',
      description: 'ZARD1994年单曲专辑，坂井泉水嗓音清澈动人，融合J-Pop与抒情摇滚，旋律深情婉转，诉说爱情中的疲惫与坚持，广受好评，巩固ZARD在日本乐坛的地位。',
      year: '1994-02-02',
      link: 'https://github.com/fightagainstdev',
    },
  },
  {
    imgSrc: '/artworks/11.jpg',
    width: 5,
    height: 3,
    position: { x: -19.5, y: 2, z: -7.5 },
    rotationY: Math.PI / 2,
    info: {
      title: 'こんなにそばに居るのに',
      artist: 'zard',
      description: 'ZARD1994年单曲专辑，坂井泉水清亮嗓音诉说爱意，融合J-Pop与抒情摇滚，旋律细腻动人，表达近在咫尺的思念，深受喜爱，巩固ZARD在日本乐坛地位。',
      year: '1994-08-08',
      link: 'https://github.com/fightagainstdev',
    },
  },
  {
    imgSrc: '/artworks/12.jpg',
    width: 5,
    height: 3,
    position: { x: -19.5, y: 2, z: 0 },
    rotationY: Math.PI / 2,
    info: {
      title: 'あなたを感じていたい',
      artist: 'zard',
      description: 'ZARD94年末单曲专辑，坂井泉水清澈嗓音传递深情，融合J-Pop与抒情摇滚，旋律温柔动人，诉说对爱的渴望与感知，广受乐迷喜爱，巩固ZARD在日本乐坛地位。',
      year: '1994-12-24',
      link: 'https://github.com/fightagainstdev',
    },
  },
  {
    imgSrc: '/artworks/13.jpg',
    width: 5,
    height: 3,
    position: { x: -19.5, y: 2, z: 7.5 },
    rotationY: Math.PI / 2,
    info: {
      title: 'Just believe in love ',
      artist: 'zard',
      description: 'ZARD1995年单曲专辑，坂井泉水清亮嗓音融合J-Pop与摇滚，旋律振奋人心，传递对爱的坚定信念，情感真挚，展现ZARD音乐的独特魅力。',
      year: '1995-02-01',
      link: 'https://github.com/fightagainstdev',
    },
  },
  {
    imgSrc: '/artworks/14.jpg',
    width: 5,
    height: 3,
    position: { x: -19.5, y: 2, z: 15 },
    rotationY: Math.PI / 2,
    info: {
      title: '愛が見えない',
      artist: 'zard',
      description: 'ZARD1995年单曲专辑，坂井泉水清澈嗓音融合J-Pop与抒情摇滚，旋律柔美动人，诉说爱情中的迷茫与追寻，情感细腻，展现ZARD音乐的独特魅力。',
      year: '1995-06-05',
      link: 'https://github.com/fightagainstdev',
    },
  },
  {
    imgSrc: '/artworks/15.jpg',
    width: 5,
    height: 3,
    position: { x: 19.5, y: 2, z: -15 },
    rotationY: -Math.PI / 2,
    info: {
      title: 'サヨナラは今もこの胸に居ます ',
      artist: 'zard',
      description: '坂井泉水清亮嗓音融合J-Pop与抒情摇滚，旋律深情婉转，诉说离别后的思念与心痛',
      year: '1995-08-28',
      link: 'https://github.com/fightagainstdev',
    },
  },
  // Right Wall (15-19)
  {
    imgSrc: '/artworks/16.jpg',
    width: 5,
    height: 3,
    position: { x: 19.5, y: 2, z: -7.5 },
    rotationY: -Math.PI / 2,
    info: {
      title: 'マイ フレンド ',
      artist: 'zard',
      description: 'ZARD96年初年单曲专辑，坂井泉水清澈嗓音融合J-Pop与摇滚，旋律轻快温暖，诉说友情的珍贵与陪伴，情感真挚，传递ZARD音乐的独特感染力。',
      year: '1996-01-08',
      link: 'https://github.com/fightagainstdev',
    },
  },
  {
    imgSrc: '/artworks/17.jpg',
    width: 5,
    height: 3,
    position: { x: 19.5, y: 2, z: 0 },
    rotationY: -Math.PI / 2,
    info: {
      title: '心を開いて',
      artist: 'zard',
      description: '作为POP ROCK风格的代表作，其明快节奏与清澈旋律交织夏日的清凉感，曾成为宝矿力主题曲',
      year: '1996-05-06',
      link: 'https://github.com/fightagainstdev',
    },
  },
  {
    imgSrc: '/artworks/18.jpg',
    width: 5,
    height: 3,
    position: { x: 19.5, y: 2, z: 7.5 },
    rotationY: -Math.PI / 2,
    info: {
      title: 'Don\'t you see!',
      artist: 'zard',
      description: 'ZARD1997年单曲专辑，坂井泉水清亮嗓音融合J-Pop与抒情摇滚，旋律柔美动人，诉说爱情中的渴望与不舍，情感细腻，传递ZARD音乐的独特感染力。',
      year: '1997-01-06',
      link: 'https://github.com/fightagainstdev',
    },
  },
  {
    imgSrc: '/artworks/19.jpg',
    width: 5,
    height: 3,
    position: { x: 19.5, y: 2, z: 15 },
    rotationY: -Math.PI / 2,
    info: {
      title: '君に逢いたくなったら…',
      artist: 'zard',
      description: 'ZARD1997年单曲专辑，坂井泉水清澈嗓音融合J-Pop与抒情摇滚，旋律温柔动人，诉说思念与重逢的渴望，情感真挚，传递ZARD音乐的独特感染力。',
      year: '1997-02-26',
      link: 'https://github.com/fightagainstdev',
    },
  },
];

